/** All available tags from HubSpot External Clips "tags" enumeration property */
export const ALL_TAGS = [
  "3D", "3D Art", "3D Pen", "3D Print", "3d drawing",
  "4 Elements", "4Th July",
  "Abstract", "Accessories", "Acrylic", "Adventure Time", "Advertisement",
  "After Effects", "AI", "Akira", "Alice In Wonderland", "Alien", "Amigurumi",
  "Among Us", "Anime", "Animals", "Animation", "Apple", "AR", "Arcane",
  "Architecture", "Ariana Grande", "Art", "Art Tools", "ASMR",
  "Attack On Titans", "Avatar", "Avocado", "Axolotl",
  "Balloon", "Bamboo", "Barbie", "Batman", "Baymax", "Beads", "Beetlejuice",
  "Bike", "Birthday", "Blue", "Bluey", "Board Games", "Books", "Bored",
  "Brainrot", "Bridgerton", "BTS", "Bubble Tea", "Budget", "Button",
  "Cake", "Cakes", "Calligraphy", "Calming", "Candles", "Capybara",
  "Cardboard", "Carebears", "Cars", "Cartoon", "Carving", "Casting", "Cats",
  "Celebrity", "Ceramic", "CGI", "Chainsaw Man", "Chalk", "Charms", "Chess",
  "Chiikawa", "Chill Guy", "China", "Chocolate", "Christmas", "Classic",
  "Classroom", "Clay", "Coffee", "Collage/Journal", "Collectibles",
  "Coloring", "Comic", "Computer", "Construction", "Cookies", "Coraline",
  "Corn", "Cosplay", "Costumes", "Craft", "Crafts", "Crazy", "Creatures",
  "Crochet", "Crocs", "Cross Stitching", "Cursed", "Customization", "Cute",
  "Dandadan", "Dandy's World", "Dark", "DC", "Deadpool", "Demon Slayer",
  "Digital", "Dinsey", "Diorama", "Disney", "Disney Princess", "DIY",
  "Dogs", "Doll House", "Dolls", "Doodle", "Doraemon", "Dragon Ball",
  "Drawing", "Drinks", "Dye Tie",
  "Easy", "easter", "Elemental", "Embroidery", "Encanto", "Epoxy",
  "Experiments", "Eyeshadow",
  "F1", "Fall", "Fantasy", "Fashion", "Felt", "Fidget", "Figurines",
  "Flipbook", "Flowers", "Fluid Art", "Fluidart", "FNAF", "Food",
  "Football", "Fortnite", "Friends", "Frogs", "Frozen", "Fruit", "Fruits",
  "Funny",
  "Game Of Thrones", "Garfield", "Genshin", "Giant", "Gift Card", "Gifts",
  "Glass", "Glow", "Glowup", "Graffiti", "Gravity Falls", "Green",
  "Grinch", "Gudetama",
  "Hacks", "Hair", "Halloween", "Harry Potter", "Hazbin Hotel",
  "Hello Kitty", "Hena", "Home Decor", "Home decoration", "Hot Wheels",
  "How to", "Hyperrealistic",
  "Ice", "Illusion", "Illusions", "Inside Out", "Iron Man",
  "Japanese", "Jelly", "Jelly cake", "Jelly Cakes", "Jelly Cat", "Jewelry",
  "Joker", "Journal", "Jujutsu Kaisen", "Jurassic Park",
  "Kawaii", "Keyboard", "Keychains", "Kids", "Kirby", "KPOP",
  "KPOP Demon Hunters",
  "Labubu", "Ladybug", "Lakers T-Shirt", "Latte Art",
  "League of Legends", "LEGO", "Lettering", "Logo", "LOL", "Lollipop",
  "Loom", "Looney Tunes", "Lord Of The Rings", "Love", "Luca",
  "M&M", "Macrame", "Madagascar", "Magic tricks", "Magnet", "Make Up",
  "Makeover", "Makeup", "Mandala", "Manga", "Marine", "Mario",
  "Marshmallow", "Marvel", "Mask", "Meme", "Metal", "Miffy", "Minecraft",
  "Miniature", "Minions", "Miraculous", "Moana", "Money Heist",
  "Monster High", "Monsters Inc", "Movies", "Mushrooms",
  "My Hero Academia", "My Little Pony",
  "Nails", "Naruto", "Nature", "Nemo", "Nintendo", "Nostalgia",
  "Oddly Satisfying", "Oil Painting", "One Piece", "Orange Color",
  "Painting", "Paper", "Party Decoration", "Peppa Pig", "Performance",
  "Perler Beads", "Pets", "Phone Case", "Photography", "Pikmin", "Pink",
  "Pipe Cleaners", "Pixar", "Pixel Art", "Plants", "Plastic",
  "Pokemon", "Polymer clay", "Pottery", "Pottery/Ceramics",
  "Power Puff Girls", "Procreate", "Product", "Purple",
  "Rainbow", "Real Or Fake", "Reborn", "Recycling", "Red", "Render",
  "Restor", "Retro", "Rick & Morty", "Roblox", "Robot", "Rock",
  "Rubiks Cube", "Rugs", "Rugs/Tufting",
  "Sand", "Sanrio", "Satisfying", "School", "Science", "Scrapbooking",
  "Sculpture", "Sesame Street", "Setup", "Sewing", "Sewing (embroidery)",
  "SFX", "Shrek", "Skibidibi", "Skillful", "Skills", "Slime", "Smiski",
  "Snoopy", "Snow", "Soap", "Sonic", "Sonny Angel", "South Park",
  "Spiderman", "Spongebob", "Sports", "Spray/Airbrush", "Squid Game",
  "Squishy", "Star Wars", "Stationery", "Steven Universe", "Stickers",
  "Stitch", "Stone", "Stop Motion", "Stopmotion", "Stranger Things",
  "Street Art", "Studio Ghibli", "Subjects", "Sugar", "Summer",
  "Super Mario", "Superheroes", "Sylvanian",
  "Tamagochi", "Tangled", "Tattoo", "Teen", "The Last Of Us",
  "The Simpsons", "Tie-Dye", "Tiktok related", "Tim Burton", "Tips&Hacks",
  "Toothless", "Tools", "Toy Story", "Toys", "Transformers", "Tree",
  "Trend", "Trends", "Trust The Process", "Tufting", "TV Series", "Twilight",
  "Unexpected", "Up",
  "Van Gogh", "Vfx", "Videogames",
  "WallE", "Watercolor", "Wax Seal", "Wednesday", "Wes Anderson", "Wicked",
  "Winnie The Pooh", "Winter", "Woman", "Wood",
  "Zelda", "zootopia",
] as const;
